AshRainK/SunStudy

- backend/.gitignore
- backend/index.js
- backend/package-lock.json
- backend/router/post.js
> Backend Initialize

- backend/package.json
> BE Initialize

- backend/.gitignore
- backend/lib/database.js
DB Encryption and insert .gitignore into DB_initialize file
*DB를 .env를 이용하여 암호화 하였습니다. (보안성 업데이트)
*gitignore 파일에 DB_initialize 파일을 추가하여 깃헙에 업데이트 하지 않도록 하였습니다.
> DB Encryption and insert .gitignore into DB_initialize file

- backend/index.js
- backend/lib/auth.js
- backend/lib/passport.js
Create auth.js & passport.js and modify index.js
* 로그인 상태인지 확인하는 auth.js 를 lib 폴더에 추가 하였습니다.
* passport를 사용하여 로그인 기능을 구현하는 passport.js를  lib 폴더에 추가 하였습니다.
* index.js의 수정할 부분들에 주석을 써놓았습니다.
> Create auth.js & passport.js and modify index.js

- frontend/package-lock.json
- frontend/package.json
* styled-components 모듈을 추가했습니다.
> Added styled-components modules

- backend/router/auth.js
- backend/router/register.js
create register.js in router & modify auth.js in router
* 회원가입 라우터인 register.js를 router에 추가 하였습니다. (id, nickname 중복체크 추가 예정)
* auth.js를 최적화 하였습니다
> create register.js in router & modify auth.js in router

- backend/lib/passport/localStrategy.js
modify localStrategy in lib/passport by using bcrypt
* localStrategy 파일을 bcrypt를 사용하여 패스워드를 비교하도록 변경하였습니다.
* localStrategy 파일의 쿼리문에서 id (num, Primary key)값을 추가로 가져오도록 수정하였습니다.
> modify localStrategy in lib/passport by using bcrypt

- backend/router/register.js
add id check & nickname check
* /router/register.js에 ID 중복 확인과 닉네임 중복 확인 라우터를 추가 하였습니다.
> add id check & nickname check

- backend/lib/passport/passport.js
modify /lib/passport/passport.js
* passport.js 파일의 deserializeUser 함수의 쿼리문을 수정하였습니다.
> modify /lib/passport/passport.js

- backend/index.js
- backend/lib/passport/passport.js
- backend/router/post.js
optimize index.js and other files
* index.js를 최적화 하였습니다.(빠져 있던 미들웨어 추가, 라우터 선언)
* /lib/passport/passport.js의 module.exports 형식을 변경하였습니다.
* /lib/passport/passport.js에 사용되었던 passport.initailize()와 passport.session()을 index.js로 옮겼습니다.
* /router/post.js에 module.exports를 추가하였습니다.
> optimize index.js and other files

- backend/index.js
optimize index.js
* index.js의 passportlib -> passportconfig으로 이름을 변경하였습니다.
* passportconfig의 경로를 수정 하였습니다.
> optimize index.js

- frontend/public/index.html
- frontend/src/App.js
- frontend/src/Screen/Join.jsx
> Created Join screen

- backend/index.js
> modify index.js

- backend/index.js
- backend/router/post.js
- backend/router/search.js
* post 라우터에 최근 글을 불러오는 기능을 추가 하였습니다.
* search 라우터를 작성 하였습니다.
* index.js에 search 라우터를 추가하였습니다.
> Modify post.js & Create search.js & add searchRouter into index.js

- frontend/public/index.html
- frontend/src/App.js
- frontend/src/Components/Header.jsx
- frontend/src/Screen/Login.jsx
- frontend/src/Screen/Postdetail.jsx
포스트 디테일 페이지를 디자인을 완성했습니다!(CSS 부분만)
+로그인, 회원가입, 로고 누르면 각 주소로 이동 가능하게 하였습니다
> postdetail page

- frontend/src/App.js
- frontend/src/Screen/Join.jsx
- frontend/src/Screen/Postingpage.jsx
> postingpage

- backend/router/auth.js
- backend/router/post.js
- backend/router/register.js
- backend/router/search.js
> modify data to payroad

- frontend/.gitignore
> Updated .gitignore

- frontend/src/Screen/Join.jsx
회원가입 페이지 로그인페이지와 같은 스타일로 수정했습니다
> 회원가입 페이지 수정했습니다

- backend/index.js
- backend/router/comment.js
- backend/router/post.js
- backend/router/register.js
- backend/router/search.js
* comment 라우터를 작성하였습니다.
* post 테이블에 장르 칼럼을 추가 하였습니다.
* index.js에 comment 라우터를 추가 하였습니다.
* 회원가입 후 자동 로그인 기능을 정상 작동하게 변경 하였습니다.
> add comment router and modify ohter router files

- backend/router/auth.js
- backend/router/comment.js
- backend/router/post.js
- backend/router/register.js
- backend/router/search.js
> modify payload

- frontend/src/Components/Header.jsx
* Changed logo click redirection url
> Updated logo click url

- backend/index.js
- backend/router/mypage.js
- backend/router/post.js
- backend/router/search.js
* 아티스트 레퍼런스를 post 테이블에 추가하였습니다.
* mypage 라우터를 생성하여 작성중입니다.
> add artist reference & create mypage router

- frontend/src/App.js
- frontend/src/Components/Header.jsx
- frontend/src/Components/Sidebar.jsx
> Created Sidebar

- backend/router/mypage.js
- backend/router/search.js
* search 라우터를 파라미터에 기반하여 검색하게 수정하였습니다.
* mypage에 자기소개를 수정 하는 기능을 추가 하였습니다.
> modify search.js and mypage.js

- frontend/src/Components/Comments.jsx
- frontend/src/Screen/Postdetail.jsx
comments 컴포넌트를 만들어 comment data를 받아올수 있게 되었습니다!
> Comments components

- backend/router/mypage.js
* 패스워드 변경 및 닉네임 변경 라우터를 추가하였습니다.
* 유저 정보를 가져오는 라우터를 작성 하였습니다.
> add update password & nickname function

- frontend/src/Components/Postingcard.jsx
post_body 대신 artist가 표시되도록 변경하였습니다.
> posting card 아티스트 부분 수정

- frontend/src/App.js
- frontend/src/Screen/Login.jsx
- frontend/src/Screen/Mypage.jsx
- frontend/src/Screen/MypageEdit.jsx
- frontend/src/setUpProxy.js
mypage 디자인 만들고 있는중입니다!
(보여지는건 요런느낌)
*mypage
*edit mypage
> mypage 디자인

- backend/router/mypage.js
* 선호 장르를 업데이트 하는 라우터를 작성하였습니다.
> add update favorite genre router

- frontend/src/Components/Comments.jsx
- frontend/src/Screen/Mypage.jsx
- frontend/src/Screen/MypageEdit.jsx
- frontend/src/Screen/Postdetail.jsx
마이페이지, 포스트디테일, 댓글창 디자인 수정하였습니다~
> 마이페이지, 포스트디테일, 댓글 디자인 수정

- frontend/src/Screen/Postdetail.jsx
postdetail 내 console.log 삭제 했습니다,,
> console.log 삭제

- backend/lib/passport/localStrategy.js
- backend/router/auth.js
* add genre to localStrategy & auth by GET
> add genre to localStrategy & auth by GET

- backend/lib/passport/localStrategy.js
> remove total_result

- backend/index.js
* POST 방식으로 서버에 요청했을 때 발생하는 CORS 에러를 수정하였습니다.
> Fixed CORS error

- frontend/src/App.js
- frontend/src/Screen/Postdetail.jsx
> comment 등록 post

- backend/router/comment.js
- backend/router/post.js
* 게시글 작성 테스트를 위해 일시적으로 req.user.id -> 201710939로 변경하였습니다.
* 댓글 작성 테스트를 위해 일시적으로 req.user.id -> 201710939로 변경하였습니다.
> Fixed for testing

- frontend/src/Screen/Join.jsx
> Join 회원가입 구현했습니다

- backend/lib/passport/passport.js
> add about_me to DB query

- frontend/src/Components/Comments.jsx
- frontend/src/Screen/Postdetail.jsx
댓글과 포스트 삭제와 수정 기능을 넣어보았습니다만,, 아직 실행은 되지 않습니다..!
> comment,post 삭제 수정 axios 기능 추가(실행x)

- backend/router/post.js
- backend/router/search.js
modify recent post router and search router
> modify recent post router and search router

- frontend/src/Components/Postingcard.jsx
- frontend/src/Screen/Home.jsx
- frontend/src/Screen/Postdetail.jsx
메인화면에서 디테일 화면으로 이동하는 기능 구현했습니다
> 메인화면에서 디테일 화면으로 이동하는 기능 구현

- backend/router/comment.js
* 댓글 수정 시와 삭제 시에 결과 값을 보내주도록 수정하였습니다.
> modify comment router

- backend/index.js
> modify session options

- backend/router/auth.js
* GET 방식을 통한 로그인 라우터에 로그인이 되어 있지 않을 때의 상태 코드를 200으로 수정 하였습니다.
> modify login by get method router's status code

- backend/router/comment.js
- backend/router/post.js
- backend/router/register.js
- backend/router/search.js
* 회원가입 라우터에 회원가입시 자동 로그인 라우터의 반환 값에 장르를 추가 하였습니다.
* 게시글 라우터에 레이팅(평점)을 추가 하였습니다.
* 게시글 라우터의 작성 및 수정 기능의 반환 값에 닉네임을 추가 하였습니다.
* 댓글 라우터의 정렬을 내림차순으로 변경 하였습니다.
* 검색 라우터에 레이팅(평점)을 추가 하였습니다.
> modify routers

- backend/router/search.js
> modify search router

- frontend/src/Screen/Postingpage.jsx
> 포스팅 페이지 장르 설정 오류 수정했습니다

- frontend/src/Screen/Join.jsx
1. join 페이지 레이아웃 수정
2. 닉네임 텍스트 박스 비어있으면 "닉네임을 입력해주세요" 창 띄우기
> join 페이지 수정했습니다

- backend/router/auth.js
* 아이디가 틀렸거나 비밀번호가 틀렸을 때의 코드를 200으로 수정 하였습니다.
> modify auth router

- backend/router/post.js
- backend/router/search.js
* 게시글 조회 라우터의 payload 형식을 변경 하였습니다.
* 검색 라우터를 파라미터 방식에서 쿼리스트링을 사용하는 방식으로 수정 하였습니다.
> modify post router and search router

- frontend/src/Screen/Login.jsx
로그인 페이지에서 회원가입 버튼 누를 시페이지 상단으로 이동
> 로그인 페이지에서 회원가입 버튼 누를 시페이지 상단으로 이동

- frontend/src/Screen/Join.jsx
- frontend/src/Screen/Postdetail.jsx
회원가입 페이지 아이디, 닉네임 체크 기능 수정했습니다.
> 회원가입 페이지 아이디, 닉네임 체크 기능 수정

- frontend/src/Components/Comments.jsx
> comment modify, delete 구현중

- frontend/src/Screen/Postingpage.jsx
포스팅 업로드 후 디테일 페이지로 가는 기능 구현했습니다
> 포스팅 업로드 후 디테일 페이지로 가는 기능 구현했습니다

- frontend/src/Components/Comments.jsx
댓글 수정과 수정 취소가 가능하게 되었습니다만,
수정 취소시 댓글 수정창에 수정을 취소하려던 댓글이 남아있는 오류가 있습니다!
빠른 시일내에 해결해 보겠습니다~
> 댓글 수정, 취소 기능 구현

- frontend/src/App.js
- frontend/src/Components/Header.jsx
- frontend/src/Screen/Search.jsx
장르별 포스팅 출력 오류 수정하였습니다.
검색 기능을 위해 서치 페이지 새로작성하였습니다.
+) 추후 검색 기능을 위해 추가 수정 필요
> 장르 페이지 수정하고 서치 페이지 작성

- frontend/src/Components/Header.jsx
> 사이드바 토글 버튼 수정

- backend/router/comment.js
댓글 작성 라우터를 로그인한 경우만 접근할 수 있도록 수정하였습니다.
> Updated comment router

- backend/index.js
> Updated session cookie setting

- frontend/src/Components/Comments.jsx
- frontend/src/Components/Header.jsx
- frontend/src/Screen/Postdetail.jsx
- frontend/src/store.js
> 로그아웃 문제 해결

- frontend/src/Components/Header.jsx
- frontend/src/Screen/Postingpage.jsx
로그인 시 헤더에 마이페이지 버튼과 새로운 포스팅 작성하는 버튼 추가하였습니다.
> 헤더에 마이페이지, 새로운 포스팅 작성 버튼 추가

- frontend/src/Components/Header.jsx
- frontend/src/Screen/MypageEdit.jsx
- frontend/src/Screen/Postingpage.jsx
> Mypage 레이아웃 수정

- backend/router/mypage.js
- frontend/src/Screen/Mypage.jsx
- frontend/src/Screen/MypageEdit.jsx
- frontend/src/Screen/Postdetail.jsx
mypageedit 닉네임 서버에서 가져오는 코드 수정했습니다.
> mypageedit 파일 수정

- frontend/src/Screen/Postdetail.jsx
게시글 삭제와 수정 기능을 추가했습니다!
_(새로고침시 수정된 게시글이 다시 원글로 돌아오는 오류가 있어 추후 수정할 계획입니다)_
> 포스트 디테일 수정

- frontend/src/App.js
- frontend/src/Screen/Mypage/Basic.jsx
- frontend/src/Screen/Mypage/Mypage.jsx
- frontend/src/Screen/Mypage/MypageEdit.jsx
> 마이페이지 레이아웃 변경

- frontend/src/Screen/Postdetail.jsx
- frontend/src/Screen/Postingpage.jsx
포스트 수정이 가능해졌습니다!
포스팅 페이지를 약간 수정하였습니다
> 포스트 수정 가능, 포스팅 페이지 수정

- frontend/src/Screen/Postdetail.jsx
- frontend/src/Screen/Postingpage.jsx
포스트에 동영상 삽입이 가능해졌습니다
포스트 수정을 통해서도 링크 수정이 가능합니다!
> 링크를 통한 게시물 영상 삽입 가능

- frontend/src/Screen/Mypage/Basic.jsx
- frontend/src/Screen/Mypage/Mypage.jsx
- frontend/src/Screen/Mypage/MypageEdit.jsx
> 마이페이지 온클릭 함수 수정 및  레이아웃 수정

- backend/router/post.js
> optimize add url function

- backend/router/post.js
> Rollback login access control

- backend/router/post.js
* 유튜브 영상에 대한 URL 파싱 코드를 삭제하였습니다.
> Update post router

- frontend/src/Components/Postingcard.jsx
- frontend/src/Screen/Postdetail.jsx
- frontend/src/Screen/Postingpage.jsx
- 모든 사람에게 수정과 삭제가 보이는 것을 해당 유저만 보이게 수정하였습니다
- 게시물 수정시 유저가 선택한 장르가 체크 되지 않는 오류를 수정하였습니다
-  댓글이 써지지 않는 오류를 수정하였습니다
+ 추후 계획
게시물 디테일 페이지의 수정 날짜, 메인 화면 날짜 수정
url이 없는 게시물에 장르에 맞는 사진을 업로드
> 게시물 수정에 관한 기능 업데이트

- frontend/src/Screen/Mypage/Basic.jsx
- frontend/src/Screen/Mypage/ChangePassword.jsx
- frontend/src/Screen/Mypage/Mypage.jsx
- frontend/src/Screen/Mypage/MypageEdit.jsx
- frontend/src/Screen/Mypage/UserPostings.jsx
마이페이지에 비밀변호 변경 파일, 포스팅 파일 추가하고 mode 추가해서 메뉴 클릭시 페이지 이동 구현
- 추가로 포스팅 불러오기 기능 필요
- 비밀번호 변경과 마이페이지 자기소개, 선호장르 보내서 마이페이지에서 보여줘야함
> 마이페이지 비밀번호 변경페이지, 포스팅 페이지 추가
